### ISSUE TITLE
Would you mind give me the cifar10 solver and net prototxt?

### ISSUE THREAD

**Issue by duanLH** [jyh2986/Active-Convolution#1]
I use the solver:
```
net: "models/ACU/ACU_train_val.prototxt"
test_iter: 100
test_interval: 500
base_lr: 0.1
momentum: 0.9
weight_decay: 0.0001
# The learning rate policy

lr_policy: "multistep"
gamma: 0.1

stepvalue: 32000
stepvalue: 48000
# Display every 100 iterations
display: 100
# The maximum number of iterations
max_iter: 64000
# snapshot intermediate results
snapshot: 10000
#snapshot_format: HDF5
snapshot_prefix: "models/ACU/ACU_iter"
# solver mode: CPU or GPU
solver_mode: GPU

```
and the net is modified from deploy file. But the final accuracy is 86%.

So, would you mind give me the solver and net files? thanks

**Comment by jyh2986** [comment]
The contents of solver are as follows, and net file is the same as deploy file in example.

```
type: "Nesterov"
base_lr: 0.1
momentum: 0.9
weight_decay: 0.0001
lr_policy: "multistep"
gamma: 0.1
stepvalue: 32000
stepvalue: 48000
max_iter:  64000
```


You mean you get that accuracy with ACU? or Naive convolution?
First, run with naive convoultion or set lr_mult to 0 for position parameters.
If you get the accuracy below 90%, you should check the input(preprocessing or something)


In this code, there's no warming up, and you should fix the positions for the first 10k iterations.
And shuffle the input randomly for every epoch.
However, this is not a major factor in performance degradation.
