### ISSUE TITLE
question about the training ACU?

### ISSUE THREAD

**Issue by carrierlxk** [jyh2986/Active-Convolution#2]
As suggested in this paper, during warm up, the learning rate should be:
  param { lr_mult: 1    decay_mult: 1 }
  param {    lr_mult: 0    decay_mult: 0  }
  param {    lr_mult: 0    decay_mult: 0  }
  param {    lr_mult: 0    decay_mult: 0  }
in first 10k iterations, then the parameters should be set as:
  param { lr_mult: 1    decay_mult: 1 }
  param {    lr_mult: 0    decay_mult: 0  }
  param {    lr_mult: 0.01    decay_mult: 0  }
  param {    lr_mult: 0.01    decay_mult: 0  }
is that right? Thank you!

**Comment by jyh2986** [comment]
You're right.
