### ISSUE TITLE
Error:  Make runtest  

### ISSUE THREAD

**Issue by DanChen001** [jyh2986/Active-Convolution#6]
@jyh2986   Thank you for sharing the code.
When I make runtest on Caffe, I meet the follow problem. Do you know how to solve it?  Thanks.

Error:
[----------] Global test environment tear-down
[==========] 2072 tests from 278 test cases ran. (1075854 ms total)
[  PASSED  ] 2069 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] AConvFastLayerTest/0.TestGradient3x3, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] AConvFastLayerTest/0.TestGradient, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] AConvFastLayerTest/0.TestGradientVariableFilter, where TypeParam = caffe::GPUDevice<float>

**Comment by jyh2986** [comment]
You should define "TEST_ACONV_FAST_ENV" macro at aconv_fast_layer.hpp for testing.

After test, please undefine the macro and make it again for real usage.

**Comment by DanChen001** [comment]
> You should define "TEST_ACONV_FAST_ENV" macro at aconv_fast_layer.hpp for testing.
> 
> After test, please undefine the macro and make it again for real usage.

@jyh2986   Thank you for your help. I will try soon.

**Comment by DanChen001** [comment]
@jyh2986   it works.  thank you!
