### ISSUE TITLE
The Settings of the parameters in aconv_param{  xxx  }  and convolution_param  {xxx}

### ISSUE THREAD

**Issue by DanChen001** [jyh2986/Active-Convolution#7]
@jyh2986   Hi，  thank you for  sharing the code.

Could you help explain the parameters of **aconv_param** and **convolution_param**  in AConvFast layer?

and how to set them?  Thanks.

**Comment by DanChen001** [comment]
In addition, how can i use a trained model with conventional convolutional layer to initialize the active convolutional layer? 

actually, i want to know how to implement the following training process:
"In early iterations, the network only learns weights with fixed shape. It then learns positions and weights concurrently. "

Thanks.

**Comment by jyh2986** [comment]
Sorry for the delayed response.

Usage of **convolution_param** is the same as the naive convolution.
**aconv_param** defines ACU specific parameters.

For most cases, it is ok to define as follows,
`aconv_param{   normalize:true   pos_filler_std: -1}`

* 'normalize:true' enable normalization of derivatives for position backward.
* 'pos_filler_std:-1' forces the initialization of the position to the grid point.
* 'position_group' is a experimental feature at this version, so I don't recommend to use it.

If you want to know more usage of parameters, please see aconv_fast_layer.cpp file.

**Comment by jyh2986** [comment]
In terms of second question,

There can be a little tricky way to achieve that strategy.

First, training with ACU setting lr_mult:0 for position parameters in given iterations.
(It is the same as the conventional convolution. You can use conventional convolution layer for this, but you should write a code to transfer convolution weights to ACU)
After that, resume the training with it with different prototxt, which is setted lr_mult greater than 0.

Or,

You can implement that feature to Caffe directly in solver codes, e.g. sgd_solver.cpp
